name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release package
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create $GITHUB_REF_NAME \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      
      - name: 'Build 📦 Package linux x64'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          pyinstaller --onefile main.py -n cli-tool-linux-x64

      - name: 'Realease package'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
            gh release upload ${tag} ./dis/cli-tool-linux-x64